apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  labels:
    datacenter: dc1
  name: amq-dc1
spec:
  acceptors:
  - name: tls-mqtt
    enabledProtocols: TLSv1.2
    expose: true
    port: 8883
    protocols: mqtt
    sslEnabled: true
    sslProvider: JDK
    # Secret is mounted on /etc/<secret-name>/
    sslSecret: tls-mqtt-secret
  - name: plain-amqp
    port: 5672
    protocols: amqp
  - name: tls-amqp
    enabledProtocols: TLSv1.2
    expose: false
    port: 5673
    protocols: amqp
    sslEnabled: true
    sslProvider: JDK
    # Secret is mounted on /etc/<secret-name>/
    sslSecret: tls-amqp-secret

  addressSettings:
    addressSetting:
    - match: '#'
      autoCreateQueues: true
      autoCreateAddresses: true
      autoDeleteQueues: true
      autoDeleteAddress: true
      maxSizeBytes: 100Mb
    - match: DLQ
      maxSizeBytes: 20Mb
    - match: ExpiryQueue
      maxSizeBytes: 20Mb
# SEE: https://github.com/apache/activemq-artemis/blob/47bcf5b73c69e3fa0f681a13801af87b534157f4/artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java#L714
# Mirror events are always stored on a local queue prefixed as "$ACTIVEMQARTEMIS_MIRROR" and then concatenated with the broker connection's configured name
# In this case: $ACTIVEMQ_ARTEMIS_MIRROR_dc1
  brokerProperties:
#  - "clusterConfiguration.dc1-cluster-config.name=dc1-cluster-config"
#  - "clusterConfigurations.my-cluster.messageLoadBalancingType=OFF_WITH_REDISTRIBUTION"
# Set TLS-MQTTacceptor autostart to OFF: it can be started when the cluster is considered ACTIVE to accept connections
#  - "acceptorConfigurations.tls-mqtt.params.autoStart=false"
  - "AMQPConnections.dc0.uri=tcp://amq-dc0-tls-amqp-${STATEFUL_SET_ORDINAL}-svc.dc0.svc.cluster.local:5673?clientFailureCheckPeriod=2000;connectionTTL=5000;sslEnabled=true;verifyHost=false;trustStorePath=/amq/extra/secrets/remote-cluster-truststore/client.ts;trustStorePassword=password"
  - "AMQPConnections.dc0.retryInterval=5000"
  - "AMQPConnections.dc0.reconnectAttempts=-1"
  - "AMQPConnections.dc0.user=amq-demo-user"
  - "AMQPConnections.dc0.password=password"
  - "AMQPConnections.dc0.autoStart=true"
  - "AMQPConnections.dc0.connectionElements.mirror.type=MIRROR"
  - "AMQPConnections.dc0.connectionElements.mirror.messageAcknowledgements=true"
  - "AMQPConnections.dc0.connectionElements.mirror.queueCreation=true"
  - "AMQPConnections.dc0.connectionElements.mirror.queueRemoval=true"
  console:
    expose: true
    sslEnabled: true
    sslSecret: tls-console-secret
  deploymentPlan:
    clustered: true
    extraMounts:
      secrets:
      - remote-cluster-truststore
    image: placeholder
    livenessProbe:
      initialDelaySeconds: 240
      timeoutSeconds: 30
    enableMetricsPlugin: true
    messageMigration: true
    persistenceEnabled: true
    podSecurity: {}
    readinessProbe:
      timeoutSeconds: 30
    requireLogin: true
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 200m
        memory: 128Mi
    size: 2
    storage:
      size: 1Gi
  upgrades:
    enabled: true
    minor: true
  version: 7.10.2
